apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: homelab
servers: 3
agents: 3
kubeAPI:
  hostPort: "6443"
image: rancher/k3s:latest
ports:
  - port: 8080:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
